### ISSUE TITLE
LogDna outage

### ISSUE THREAD

**Issue by pupitooo** [fusionspim/monolog-logdna#10]
Is there any option how to solve situation when logdna is down?
I down know what is correct solution for this situation. I have no problem to create PR, but I want to discuss possible (and correct) solutions for this before I will start to do some fixes.

My suggestion is to try send request 5 times and then log error message some other way.
Thank you for your ideas.

**Comment by ziadoz** [comment]
@pupitooo You can configure retries by passing in your own pre-configured Guzzle client instance to the handler. I haven't tested this code myself, but it should point you in the right direction:

```
$calls = 0;
$decider = function ($retries, $request, $response, $error) use (&$calls) {
    return count($calls) < 5;
};

$delay = function ($retries, $response) {
    return 1;
};

$middleware = GuzzleHttp\Middleware::retry($decider, $delay);
$client = new GuzzleHttp\Client([
    'timeout' => 5, 
    'handler' => $middleware(GuzzleHttp\HandlerStack::create()),
]);

$handler = new Fusions\Monolog\LogDna\Handler\LogDnaHandler(getenv('LOGDNA_INGESTION_KEY'), 'host');
$handler->setHttpClient($client);
```

You might also want to look at using Monolog's `WhatFailureGroupHandler` handler, which allows you to configure handlers to fallback on. You can use this to log to a file if LogDNA absolutely can't be reached for example:

```
new WhatFailureGroupHandler([
    $logDnaHandler,
    $fileHandler,
    $stdErrHandler,
]);
```
